//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservations.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accommodations()
        {
            this.Rooms = new HashSet<Rooms>();
            this.User_accommodations = new HashSet<User_accommodations>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string NIP { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string number { get; set; }
        public string phone_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rooms> Rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_accommodations> User_accommodations { get; set; }
    }
}
