//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservations.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms_pictures
    {
        public int id { get; set; }
        public Nullable<int> id_room { get; set; }
        public Nullable<int> id_picture { get; set; }
    
        public virtual Pictures Pictures { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
